package com.flagpicker.utils;

public class Constants {
  public enum ReturnCode {
    SUCCESS, ERROR, INVALIDINPUT, UNAUTHORIZED, DATANOTFOUND, SYSTEMERROR, NAMEALREADYEXISTS, FILECOPYERROR, FAILED, NODATAFOUND, INVALIDOPERATION, DUPLICATEDATA, DATA_TRANSFER_IN_PROGRESS, PROCESSING_TESTMAP, TESTNUMBER_ALREADY_INGESTED
  }
}
